kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: prometheus-operator-all-any
  namespace: system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-operator
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
