apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: system
spec:
  chart:
    spec:
      chart: ./fluxcd/charts/prometheus-community/kube-prometheus-stack
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
  interval: 5m0s
  values:
    fullnameOverride: prometheus
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    prometheusOperator:
      admissionWebhooks:
        certManager:
          enabled: true
        patch:
          image:
            registry: ${REGISTRY%/}
      image:
        registry: ${REGISTRY%/}
      prometheusConfigReloader:
        image:
          registry: ${REGISTRY%/}
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: "0"
            memory: "0"
      thanosImage:
        registry: ${REGISTRY%/}
        repository: thanos/thanos
    prometheus:
      enabled: false
    prometheus-node-exporter:
      fullnameOverride: node-exporter
      # podLabels:
      #   app.kubernetes.io/name: node-exporter
      image:
        registry: ${REGISTRY%/}
        repository: prometheus/node-exporter
      nodeSelector:
        kubernetes.io/os: linux
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
      image:
        registry: ${REGISTRY%/}
    kubeControllerManager:
      serviceMonitor:
        insecureSkipVerify: true
    kubeEtcd:
      enabled: false
    kubeScheduler:
      serviceMonitor:
        insecureSkipVerify: true
    kubeProxy:
      enabled: false
    defaultRules:
      create: true
