version: "3"

tasks:

  nixos:switch:
    desc: Switches nixos configuration
    dir: "{{.ROOT_DIR}}"
    env:
      NIXPKGS_ALLOW_UNFREE: "1"
    requires:
      vars:
        - NAME
    cmds:
      - sudo nixos-rebuild switch --flake .#{{.NAME}} --impure

  home:switch:
    desc: Switches home-manager configuration
    dir: "{{.ROOT_DIR}}"
    env:
      NIXPKGS_ALLOW_UNFREE: "1"
    requires:
      vars:
        - NAME
    cmds:
      - nix run home-manager/master -- switch --flake .#{{.NAME}} -b backup --impure
