version: "3"

vars:
  USER: '{{.USER | default "roku"}}'
  USER_NAME: '{{.USER_NAME | default "Roman Kuznetsov"}}'

tasks:

  nixos:switch:
    desc: Switches nixos configuration
    dir: "{{.ROOT_DIR}}"
    env:
      NIXPKGS_ALLOW_UNFREE: "1"
      NIX_USER: "{{.USER}}"
      NIX_USER_NAME: "{{.USER_NAME}}"
    requires:
      vars:
        - NAME
    cmds:
      - sudo nixos-rebuild switch --flake .#{{.NAME}} --impure

  home-manager:switch:
    desc: Switches home-manager configuration
    dir: "{{.ROOT_DIR}}"
    env:
      NIXPKGS_ALLOW_UNFREE: "1"
      NIX_USER: "{{.USER}}"
      NIX_USER_NAME: "{{.USER_NAME}}"
    requires:
      vars:
        - NAME
    cmds:
      - nix run home-manager/master -- switch --flake .#{{.NAME}} -b backup --impure
