apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: system
spec:
  chart:
    spec:
      chart: ./fluxcd/charts/ingress-nginx/ingress-nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  interval: 5m0s
  values:
    controller:
      # watchIngressWithoutClass: true
      resources:
        limits:
          cpu: "0"
          memory: "0"
        requests:
          cpu: "0"
          memory: "0"
      admissionWebhooks:
        enabled: false
        patch:
          image:
            digest: ""
            registry: ${REGISTRY//\//}
      podAnnotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
      image:
        digest: ""
        registry: ${REGISTRY//\//}
      electionID: ingress-controller-leader-nginx
      ingressClass: nginx
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx
        default: true
        enabled: true
        name: nginx
      metrics:
        enabled: true
    defaultBackend:
      enabled: false
    fullnameOverride: ingress-nginx
