# ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  enableAdminAPI: false
  externalUrl: /monitoring/prometheus
  externalLabels:
    cluster: ${CLUSTER_NAME}
    cluster_id: ${CLUSTER_NAME} #For Kubecost https://guide.kubecost.com/hc/en-us/articles/4407595964695#option-b-out-of-cluster-storage-thanos
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager-operated
        port: web
  image: ${REGISTRY}prometheus/prometheus:v2.47.2
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: prometheus-operator
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prometheus-operator
  remoteWrite: []
  replicas: 1
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: prometheus-operator
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  additionalScrapeConfigs:
    name: prometheus-additional-scrape-configs
    key: prometheus-additional-scrape-configs.yaml
  additionalAlertRelabelConfigs:
    name: prometheus-additional-alert-relabel-configs
    key: prometheus-additional-alert-relabel-configs.yaml
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prometheus-operator
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 40Gi
  shards: 1
  version: v2.47.2
