apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: system-namespace
    - name: secrets-store-csi-driver
  interval: 10m0s
  timeout: 5m0s
  path: ./fluxcd/catalog/system/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: system
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: system
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: cert-manager-csi-driver
      namespace: system
