apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: system-namespace
  interval: 10m0s
  timeout: 5m0s
  path: ./fluxcd/catalog/system/grafana-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: grafana-operator
      namespace: system
