apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  dependsOn:
    - name: system-namespace
  interval: 10m0s
  timeout: 5m0s
  path: ./fluxcd/catalog/system/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metrics-server
      namespace: system
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: metrics-server
          namespace: system
        spec:
          values:
            replicas: 1
      target:
        kind: HelmRelease
        name: metrics-server
        namespace: system
