apiVersion: v1
kind: Secret
metadata:
  name: cluster
  namespace: flux-system
type: Opaque
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:jFFy8+4=,iv:43zdj42bljpFWOZK3YRkF2izEaRIEarGz3ujIhHc1WQ=,tag:TzIc3gIncwqGK1/WhWbfhg==,type:str]
  REGISTRY: ENC[AES256_GCM,data:wETZm8aSHWyRgu3fFAJl,iv:NBKN5gav6tGs+cZllrk6Z17PEOFBKh8aNN9g+CDpdNo=,tag:4wQ87W5PXtMJDqY5tdLtvw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1sawl9lzslp6l9eugvn025ecznumkgswcl8cj8t5xh76k8dt7gsxqfqs0ky
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISWZObDNqYVJMdHdyMEha
        TkF2TEVSRzh6NnFjOGhPQkxXbm93b1FYVHk0CnFTT1NKaklCNVF4NU9od2k0Z1FV
        dTFzMjdoVkt3ZExZNlpBSzJKUmhWMmcKLS0tIExkRVZzUGVoYXJrTVJmaTczRkw1
        TU5QZ1JyK2VtbE1uWW45V2tKV0kwZzQK/B9yAuFE17FH5zcVvqX5tUXJwg36c/D3
        8Yd0S64rxqWXuBeXyGSZPGjlnFnEvBXv3uGlV7TST1W/zmkz5gw24g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-28T12:23:02Z"
  mac: ENC[AES256_GCM,data:c+4/jP1XMuTYj44Cj0g1mg0J6zuTXZ0YFd9Dm/N6RDx3eJfuUzKLOk4hkfwk26P7GJzdWWnSXAvqMZzHIh62m0AEsKrdadudEbMppdWD9h+WP7yWbo+MBMkeVpItgafmk8dv3+nFSSMreOX+K1fv+5pXrJR6fkPPlo7+dmt+hn4=,iv:iXDBG8qfugkttqZH3uu00i6yBegnVsw1NEZ2iz+l/e8=,tag:MoE7MRZMh97+Lh+9sUn8vQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
