apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    isDefault: true
    access: proxy
    name: Prometheus
    type: prometheus
    url: http://prometheus-operated:9090
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    # editable: true
