apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: system
spec:
  chart:
    spec:
      chart: ./fluxcd/charts/secrets-store-csi-driver/secrets-store-csi-driver
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  interval: 5m0s
  values:
    fullnameOverride: secrets-store-csi-driver
    syncSecret:
      enabled: true
    enableSecretRotation: true
    linux:
      image:
        repository: ${REGISTRY}csi-secrets-store/driver
      crds:
        image:
          repository: ${REGISTRY}csi-secrets-store/driver-crds
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      registrarImage:
        repository: ${REGISTRY}sig-storage/csi-node-driver-registrar
      livenessProbeImage:
        repository: ${REGISTRY}sig-storage/livenessprobe
      tolerations:
        - operator: Exists
      driver:
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      registrar:
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      livenessProbe:
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
