apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-namespace
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  path: ./fluxcd/catalog/monitoring/namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster
  patches:
    - patch: |-
        apiVersion: v1
        kind: LimitRange
        metadata:
          name: cpu-limit-range
          namespace: monitoring
        spec:
          limits: []
      target:
        kind: LimitRange
        name: cpu-limit-range
        namespace: monitoring
    - patch: |-
        apiVersion: v1
        kind: LimitRange
        metadata:
          name: mem-limit-range
          namespace: monitoring
        spec:
          limits: []
      target:
        kind: LimitRange
        name: mem-limit-range
        namespace: monitoring
