apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: system
spec:
  chart:
    spec:
      chart: ./fluxcd/charts/grafana-operator/grafana-operator
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  interval: 5m0s
  values:
    fullnameOverride: grafana-operator
    image:
      repository: ${REGISTRY}grafana/grafana-operator
    namespaceScope: false
    leaderElect: false
    watchNamespaces: ""
