apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: "${CLUSTER_NAME}@playground.com"
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: letsencrypt
#     # Enable the HTTP-01 challenge provider
#     solvers:
#       - http01:
#           ingress:
#             class: nginx
#             ingressTemplate:
#               metadata:
#                 annotations:
#                   kubernetes.io/ingress.class: nginx
#                   acme.cert-manager.io/http01-ingress-class: nginx
