apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: system
spec:
  chart:
    spec:
      chart: ./fluxcd/charts/jetstack/cert-manager
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  interval: 5m0s
  values:
    extraArgs:
      - --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.16.3
    cainjector:
      enabled: true
    fullnameOverride: cert-manager
    installCRDs: true
    prometheus:
      enabled: true

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver
  namespace: system
spec:
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: ./fluxcd/charts/jetstack/cert-manager-csi-driver
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  interval: 5m0s
  values:
    tolerations:
      - operator: Exists
