# TODO: after upgrading cert-manager chart next time, make sure
#       to check and if PDB was introduced, enable it in non-local profiles

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: system
spec:
  chart:
    spec:
      chart: ./fluxcd/charts/jetstack/cert-manager
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  interval: 5m0s
  values:
    image:
      repository: ${REGISTRY}jetstack/cert-manager-controller
      tag: v1.13.2
    extraArgs:
      - --acme-http01-solver-image=${REGISTRY}jetstack/cert-manager-acmesolver:v1.13.2
    cainjector:
      enabled: true
      image:
        repository: ${REGISTRY}jetstack/cert-manager-cainjector
        tag: v1.13.2
    fullnameOverride: cert-manager
    installCRDs: true
    prometheus:
      enabled: true
    webhook:
      image:
        repository: ${REGISTRY}jetstack/cert-manager-webhook
        tag: v1.13.2
    startupapicheck:
      image:
        repository: ${REGISTRY}jetstack/cert-manager-ctl
        tag: v1.13.2

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver
  namespace: system
spec:
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: ./fluxcd/charts/jetstack/cert-manager-csi-driver
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  interval: 5m0s
  values:
    image:
      repository: ${REGISTRY}jetstack/cert-manager-csi-driver
      tag: v0.5.0
    nodeDriverRegistrarImage:
      repository: ${REGISTRY}sig-storage/csi-node-driver-registrar
      tag: v2.8.0
    livenessProbeImage:
      repository: ${REGISTRY}sig-storage/livenessprobe
      tag: v2.10.0
    tolerations:
      - operator: Exists
