{ pkgs, pkgs-stable, ... }:

{
  home.packages = with pkgs;
    [
      bat
      btop
      claude-code
      cmatrix
      eza
      fd
      ffmpegthumbnailer
      fish
      flux
      gcc
      gitFull
      gnupg
      go-task
      (pkgs.callPackage ./pkgs/k9s { }) # k9s
      kubectl
      kubeswitch
      lan-mouse
      lazydocker
      lazygit
      mc
      neofetch
      nerd-fonts.envy-code-r
      nerd-fonts.fantasque-sans-mono
      nerd-fonts.hurmit
      nerd-fonts.iosevka
      nerd-fonts.iosevka-term
      nerd-fonts.iosevka-term-slab
      nerd-fonts.jetbrains-mono
      nerd-fonts.lekton
      nerd-fonts.meslo-lg
      nerd-fonts.monaspace
      nerd-fonts.monofur
      nerd-fonts.mononoki
      nerd-fonts.space-mono
      nerd-fonts.ubuntu
      nerd-fonts.ubuntu-mono
      nerd-fonts.ubuntu-sans
      nodejs_24
      pass
      podman
      podman-compose
      podman-tui
      poppler
      ripgrep
      rsync
      tree
      tree-sitter
      tt
      vim
      wl-clipboard
      xclip
      zoxide
      zsh
    ] ++ (with pkgs-stable; [ yazi ]);
}
