{
 "title": "Persistent Volumes",
 "description": "Monitors all persistent volumes that exists within a Kubernetes cluster. Prometheus is used as datasource. ",
 "tags": [ "system" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "k8s_cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "k8s_namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PVCs Full in 2 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}[1d], 2 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 5 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}[1d], 5 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 1 Week - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "kube_storageclass_info" }
   ]
  },
  {
   "title": "PVCs Above Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"} )) >= (${warning_threshold} / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Usage statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,storageclass,persistentvolumeclaim,volumename) (kube_persistentvolumeclaim_info{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\"})"
    },
    {
     "expr": "sum by (cluster,persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (cluster,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (cluster,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum by (cluster,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}/kubelet_volume_stats_capacity_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"} * 100)"
    }
   ]
  },
  {
   "title": "Graphical usage data ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All Running PVCs Used Bytes",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace,cluster) (kubelet_volume_stats_used_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}))",
       "legendFormat": "{{cluster}} :: {{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hourly Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}[1h])",
       "legendFormat": "{{cluster}} :: {{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}[1d])",
       "legendFormat": "{{cluster}} :: {{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Weekly Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{cluster=~\"${k8s_cluster}\",namespace=~\"${k8s_namespace}\",job=\"nodes\"}[1w])",
       "legendFormat": "{{cluster}} :: {{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  }
 ]
}