apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cnpg-allow-any
  namespace: system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: cnpg
      app.kubernetes.io/name: cloudnative-pg
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
