apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: system
spec:
  chart:
    spec:
      chart: ./fluxcd/charts/cnpg/cloudnative-pg
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  interval: 5m0s
  values: {}
