kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: metrics-server-allow-any
  namespace: system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
